const char *footer = 
  "/* begin footer.template */\n"
  "\n"
  "#ifndef YY_PART\n"
  "\n"
  "typedef int (*yyrule)(GREG *G);\n"
  "\n"
  "YY_PARSE(int) YY_NAME(parse_from)(GREG *G, yyrule yystart)\n"
  "{\n"
  "  int yyok;\n"
  "  if (!G->buflen)\n"
  "    {\n"
  "      G->buflen= YY_BUFFER_START_SIZE;\n"
  "      G->buf= (char*)YY_ALLOC(G->buflen, G->data);\n"
  "      G->textlen= YY_BUFFER_START_SIZE;\n"
  "      G->text= (char*)YY_ALLOC(G->textlen, G->data);\n"
  "      G->thunkslen= YY_STACK_SIZE;\n"
  "      G->thunks= (yythunk*)YY_ALLOC(sizeof(yythunk) * G->thunkslen, G->data);\n"
  "      G->valslen= YY_STACK_SIZE;\n"
  "      G->vals= (YYSTYPE*)YY_ALLOC(sizeof(YYSTYPE) * G->valslen, G->data);\n"
  "      G->begin= G->end= G->pos= G->limit= G->thunkpos= 0;\n"
  "    }\n"
  "  G->pos = 0;\n"
  "  G->begin= G->end= G->pos;\n"
  "  G->thunkpos= 0;\n"
  "  G->val= G->vals;\n"
  "  yyok= yystart(G);\n"
  "  if (yyok) yyDone(G);\n"
  "  yyCommit(G);\n"
  "  return yyok;\n"
  "  (void)yyrefill;\n"
  "  (void)yymatchDot;\n"
  "  (void)yymatchChar;\n"
  "  (void)yymatchString;\n"
  "  (void)yymatchClass;\n"
  "  (void)yyDo;\n"
  "  (void)yyText;\n"
  "  (void)yyDone;\n"
  "  (void)yyCommit;\n"
  "  (void)yyAccept;\n"
  "  (void)yyPush;\n"
  "  (void)yyPop;\n"
  "  (void)yySet;\n"
  "}\n"
  "\n"
  "/*\n"
  "YY_PARSE(int) YY_NAME(parse)(GREG *G)\n"
  "{\n"
  "  return YY_NAME(parse_from)(G, yy_%s);\n"
  "}\n"
  "*/\n"
  "\n"
  "YY_PARSE(void) YY_NAME(init)(GREG *G)\n"
  "{\n"
  "    memset(G, 0, sizeof(GREG));\n"
  "}\n"
  "YY_PARSE(void) YY_NAME(deinit)(GREG *G)\n"
  "{\n"
  "    if (G->buf) YY_FREE(G->buf);\n"
  "    if (G->text) YY_FREE(G->text);\n"
  "    if (G->thunks) YY_FREE(G->thunks);\n"
  "    if (G->vals) YY_FREE(G->vals);\n"
  "}\n"
  "YY_PARSE(GREG *) YY_NAME(parse_new)(YY_XTYPE data)\n"
  "{\n"
  "  GREG *G = (GREG *)YY_CALLOC(1, sizeof(GREG), G->data);\n"
  "  G->data = data;\n"
  "  return G;\n"
  "}\n"
  "\n"
  "YY_PARSE(void) YY_NAME(parse_free)(GREG *G)\n"
  "{\n"
  "  YY_NAME(deinit)(G);\n"
  "  YY_FREE(G);\n"
  "}\n"
  "\n"
  "#endif\n"
  "\n"
  "/* end footer.template */\n"
;
